name: goreleaser

on: [push,pull_request]

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Setup Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '2.0.x'
      -
        name: Run Script
        run:
          .github/workflows/build/build.bat

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: tmp/*
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}